Month = int(input('Specify month with a number between 1-12:'))

if Month == 1:print('January')
if Month == 2:print('February')
if Month == 3:print('March')
if Month == 4:print('April')
if Month == 5:print('May')
if Month == 6:print('June')
if Month == 7:print('July')
if Month == 8:print('August')
if Month == 9:print('September')
if Month == 10:print('October')
if Month == 11:print('November')
if Month == 12:print('December')